logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.SseEmitter=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
